name: FWKotlinDeps
version: "0.0.7"
api-version: "1.16"
description: Plugin for handling dependencies for the ForgottenWorld project Kotlin plugins
author: Shivs (OhMeMuffin)
main: it.forgottenworld.kotlindeps.FWKotlinDepsPlugin
